---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sharing.app.fullname" . }}
  labels: {{- include "sharing.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: app
      port: {{ .Values.app.proxyPort }}
      targetPort: 8080
  selector: {{- include "sharing.app.selectorLabels" . | nindent 4 }}


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sharing.app.fullname" . }}
  labels: {{- include "sharing.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.app.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "sharing.app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "sharing.app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: sharing
        image: kotosiro/sharing:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: KOTOSIRO_DB_URL
            value: postgres://postgres:{{ .Values.db.password | b64enc }}@{{ include "sharing.db.fullname" . }}:5432/sharing
          - name: KOTOSIRO_SERVER_ADDR
            value: http://127.0.0.1:8080
          - name: KOTOSIRO_SERVER_BIND
            value: 0.0.0.0:8080
          - name: KOTOSIRO_ADMIN_NAME
            value: {{ .Values.app.adminName }}
          - name: KOTOSIRO_ADMIN_EMAIL
            value: {{ .Values.app.adminEmail }}
          - name: KOTOSIRO_ADMIN_PASSWORD
            value: {{ .Values.app.adminPassword }}
          - name: KOTOSIRO_ADMIN_NAMESPACE
            value: {{ .Values.app.adminNamespace }}
          - name: KOTOSIRO_ADMIN_TTL
            value: {{ .Values.app.adminTtl }}
          - name: KOTOSIRO_SIGNED_URL_TTL
            value: {{ .Values.app.signedUrlTtl }}
          - name: KOTOSIRO_JWT_SECRET
            value: {{ .Values.app.jwtSecret }}
          - name: KOTOSIRO_AWS_PROFILE
            value: {{ .Values.app.awsProfile }}
          - name: KOTOSIRO_AWS_REGION
            value: {{ .Values.app.awsRegion }}
          - name: KOTOSIRO_USE_JSON_LOG
            value: {{ .Values.app.useJsonLog }}
          - name: KOTOSIRO_LOG_FILTER
            value: {{ .Values.app.logFilter }}
