---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sharing.db.fullname" . }}
  labels: {{- include "sharing.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: db
      port: 5432
      targetPort: 5432
  selector: {{- include "sharing.db.selectorLabels" . | nindent 4 }}


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sharing.db.fullname" . }}
  labels: {{- include "sharing.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.db.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "sharing.db.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "sharing.db.fullname" . }}
  template:
    metadata:
      labels: {{- include "sharing.db.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: postgres
          image: postgres:alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: sharing
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db.password | b64enc }}
          resources: {}
          volumeMounts:
            - name: {{ include "sharing.db.fullname" . }}
              mountPath: /var/lib/postgres/data
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: {{ include "sharing.db.fullname" . }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.db.storageSize }}
